/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IHeroiconsOutlineHome: typeof import("~icons/heroicons-outline/home")["default"]
    IMdiAccount: typeof import("~icons/mdi/account")["default"]
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    QuestionsList: typeof import('./src/components/QuestionsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
